services:
  - type: web
    name: warranty-submissions
    env: node
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GMAIL_SEARCH_QUERY
        sync: false
      - key: RETENTION_PERIOD
        value: "5"
    cron:
      - schedule: "0 0 * * *"
        command: node cleanup.js 